In [1]:
import pandas as pd
import numpy as np
import tensorflow

In [2]:
df=pd.read_excel("Student_Assignments_Dataset (1).xlsx")

In [3]:
df

ID                                               Text       Category
0         1  Global warming is primarily caused by the burn...    Plagiarized
1         2  Global warming is primarily caused by the burn...    Plagiarized
2         3  Climate change is one of the most pressing cha...  Human-Written
3         4  The Renaissance was a period of cultural and a...    Plagiarized
4         5  Global warming is primarily caused by the burn...    Plagiarized
...     ...                                                ...            ...
9995   9996  Machine learning is a subset of AI that focuse...   AI-Generated
9996   9997  The Renaissance was a period of cultural and a...    Plagiarized
9997   9998  The Industrial Revolution was a pivotal era th...  Human-Written
9998   9999  Global warming is primarily caused by the burn...    Plagiarized
9999  10000  Artificial Intelligence is transforming indust...   AI-Generated

[10000 rows x 3 columns]

In [5]:
df["Text"][0]

"Global warming is primarily caused by the burning of fossil fuels, which releases greenhouse gases into the atmosphere. These gases trap heat, causing Earth's temperature to rise. This phenomenon has led to severe environmental impacts like rising "

In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [7]:
token=Tokenizer(oov_token="<OOV>")

In [8]:
corpus=[]
for x in df["Text"]:
    corpus.append(x)


In [9]:
corpus

["Global warming is primarily caused by the burning of fossil fuels, which releases greenhouse gases into the atmosphere. These gases trap heat, causing Earth's temperature to rise. This phenomenon has led to severe environmental impacts like rising ",
 "Global warming is primarily caused by the burning of fossil fuels, which releases greenhouse gases into the atmosphere. These gases trap heat, causing Earth's temperature to rise. This phenomenon has led to severe environmen",
 'Climate change is one of the most pressing challenges of our time. Human activities such as deforestation and the burning of fossil fuels have resulted in increased greenhouse gas emissions. This has led t',
 'The Renaissance was a period of cultural and artistic flourishing in Europe, marked by significant advancements in art, literature, and science. Renowned figures like Leonardo da Vinci and Michelangelo made lasting contributions to art and innovation.',
 "Global warming is primarily caused by the burning 

In [10]:
label=df["Category"]

In [11]:
label.unique()

array(['Plagiarized', 'Human-Written', 'AI-Generated'], dtype=object)

In [12]:
labels=['AI-Generated', 'Human-Written', 'Plagiarized']

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
label=le.fit_transform(label)

In [14]:
type(label)

numpy.ndarray

In [15]:
token.fit_on_texts(corpus)

In [16]:
corpus

["Global warming is primarily caused by the burning of fossil fuels, which releases greenhouse gases into the atmosphere. These gases trap heat, causing Earth's temperature to rise. This phenomenon has led to severe environmental impacts like rising ",
 "Global warming is primarily caused by the burning of fossil fuels, which releases greenhouse gases into the atmosphere. These gases trap heat, causing Earth's temperature to rise. This phenomenon has led to severe environmen",
 'Climate change is one of the most pressing challenges of our time. Human activities such as deforestation and the burning of fossil fuels have resulted in increased greenhouse gas emissions. This has led t',
 'The Renaissance was a period of cultural and artistic flourishing in Europe, marked by significant advancements in art, literature, and science. Renowned figures like Leonardo da Vinci and Michelangelo made lasting contributions to art and innovation.',
 "Global warming is primarily caused by the burning 

In [17]:
token.word_index

{'<OOV>': 1,
 'and': 2,
 'the': 3,
 'to': 4,
 'of': 5,
 'like': 6,
 'in': 7,
 'is': 8,
 'by': 9,
 'a': 10,
 'led': 11,
 'economies': 12,
 'was': 13,
 'marked': 14,
 'that': 15,
 'burning': 16,
 'fossil': 17,
 'fuels': 18,
 'greenhouse': 19,
 'this': 20,
 'has': 21,
 'ai': 22,
 'gases': 23,
 'on': 24,
 'have': 25,
 'global': 26,
 'warming': 27,
 'causing': 28,
 'art': 29,
 'it': 30,
 'machine': 31,
 'learning': 32,
 'significant': 33,
 'patterns': 34,
 'rising': 35,
 'sea': 36,
 'levels': 37,
 'extreme': 38,
 'weather': 39,
 'revolution': 40,
 'industrial': 41,
 'pivotal': 42,
 'era': 43,
 'reshaped': 44,
 'societies': 45,
 'transition': 46,
 'from': 47,
 'agrarian': 48,
 'industrialized': 49,
 'ones': 50,
 'innovations': 51,
 'steam': 52,
 'engine': 53,
 'mechanized': 54,
 'change': 55,
 'climate': 56,
 'one': 57,
 'most': 58,
 'pressing': 59,
 'challenges': 60,
 'our': 61,
 'time': 62,
 'human': 63,
 'activities': 64,
 'such': 65,
 'as': 66,
 'deforestation': 67,
 'resulted': 68,
 'in

In [18]:
sequences = token.texts_to_sequences(corpus)

In [20]:
import json

In [21]:
tokenizer_json = token.to_json()
with open("tokenizer.json", "w") as json_file:
    json.dump(tokenizer_json, json_file)

In [18]:
sequences

[[26,
  27,
  8,
  104,
  105,
  9,
  3,
  16,
  5,
  17,
  18,
  106,
  107,
  19,
  23,
  108,
  3,
  109,
  110,
  23,
  111,
  112,
  28,
  113,
  114,
  4,
  115,
  20,
  116,
  21,
  11,
  4,
  140,
  148,
  153,
  6,
  35],
 [26,
  27,
  8,
  104,
  105,
  9,
  3,
  16,
  5,
  17,
  18,
  106,
  107,
  19,
  23,
  108,
  3,
  109,
  110,
  23,
  111,
  112,
  28,
  113,
  114,
  4,
  115,
  20,
  116,
  21,
  11,
  4,
  140,
  236],
 [56,
  55,
  8,
  57,
  5,
  3,
  58,
  59,
  60,
  5,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  2,
  3,
  16,
  5,
  17,
  18,
  25,
  68,
  7,
  69,
  19,
  70,
  71,
  20,
  21,
  11,
  173],
 [3,
  90,
  13,
  10,
  91,
  5,
  92,
  2,
  93,
  94,
  7,
  95,
  14,
  9,
  33,
  96,
  7,
  29,
  97,
  2,
  98,
  99,
  100,
  6,
  101,
  102,
  103,
  2,
  134,
  137,
  141,
  150,
  4,
  29,
  2,
  161],
 [26,
  27,
  8,
  104,
  105,
  9,
  3,
  16,
  5,
  17,
  18,
  106,
  107,
  19,
  23,
  108,
  3,
  109,
  110,
  23,
  111,
  112,
  28,
 

In [19]:
sequences

[[26,
  27,
  8,
  104,
  105,
  9,
  3,
  16,
  5,
  17,
  18,
  106,
  107,
  19,
  23,
  108,
  3,
  109,
  110,
  23,
  111,
  112,
  28,
  113,
  114,
  4,
  115,
  20,
  116,
  21,
  11,
  4,
  140,
  148,
  153,
  6,
  35],
 [26,
  27,
  8,
  104,
  105,
  9,
  3,
  16,
  5,
  17,
  18,
  106,
  107,
  19,
  23,
  108,
  3,
  109,
  110,
  23,
  111,
  112,
  28,
  113,
  114,
  4,
  115,
  20,
  116,
  21,
  11,
  4,
  140,
  236],
 [56,
  55,
  8,
  57,
  5,
  3,
  58,
  59,
  60,
  5,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  2,
  3,
  16,
  5,
  17,
  18,
  25,
  68,
  7,
  69,
  19,
  70,
  71,
  20,
  21,
  11,
  173],
 [3,
  90,
  13,
  10,
  91,
  5,
  92,
  2,
  93,
  94,
  7,
  95,
  14,
  9,
  33,
  96,
  7,
  29,
  97,
  2,
  98,
  99,
  100,
  6,
  101,
  102,
  103,
  2,
  134,
  137,
  141,
  150,
  4,
  29,
  2,
  161],
 [26,
  27,
  8,
  104,
  105,
  9,
  3,
  16,
  5,
  17,
  18,
  106,
  107,
  19,
  23,
  108,
  3,
  109,
  110,
  23,
  111,
  112,
  28,
 

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,ReLU,Dropout,LSTM,Embedding,BatchNormalization,Bidirectional
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2

In [21]:
vocab_size=415
embedding_dims=300
sequence_length=200
dropout_rate=0.3
learning_rate = 0.001   

In [22]:
from tensorflow.keras.utils import pad_sequences

In [23]:
pad_sequenced=pad_sequences(sequences, maxlen=sequence_length, padding='post')

In [24]:
pad_sequenced

array([[26, 27,  8, ...,  0,  0,  0],
       [26, 27,  8, ...,  0,  0,  0],
       [56, 55,  8, ...,  0,  0,  0],
       ...,
       [ 3, 41, 40, ...,  0,  0,  0],
       [26, 27,  8, ...,  0,  0,  0],
       [72, 73,  8, ...,  0,  0,  0]])

In [25]:
# Model Definition
# Model Definition
model = Sequential()

# Embedding Layer
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dims, input_length=sequence_length))

# LSTM Layers with Batch Normalization and Dropout
model.add(Bidirectional(LSTM(64, activation="relu", return_sequences=True, kernel_regularizer='l2')))
model.add(BatchNormalization())
model.add(Dropout(dropout_rate))

model.add(Bidirectional(LSTM(128, activation="relu", return_sequences=True, kernel_regularizer='l2')))  # Change to return_sequences=False
model.add(BatchNormalization())
model.add(Dropout(dropout_rate))

model.add(Bidirectional(LSTM(256, activation="relu", return_sequences=True, kernel_regularizer='l2')))
model.add(BatchNormalization())
model.add(Dropout(dropout_rate))

model.add(Bidirectional(LSTM(512, activation="relu", return_sequences=False, kernel_regularizer='l2')))
model.add(BatchNormalization())
model.add(Dropout(dropout_rate))

# Dense Output Layer
model.add(Dense(units=512,activation="relu"))
model.add(Dropout(dropout_rate))
model.add(Dense(units=128,activation="relu"))
model.add(Dropout(dropout_rate))
# Dense Output Layer
model.add(Dense(units=64,activation="relu"))
model.add(Dropout(dropout_rate))

model.add(Dense(units=3, activation="softmax"))


C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional (Bidirectional)        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ ?                           │     0 (unbuilt) │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional_1 (Bidirectional)      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ ?                           │     0 (unbuilt) │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional_2 (Bidirectional)      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ ?                           │     0 (unbuilt) │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional_3 (Bidirectional)      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_3                │ ?                           │     0 (unbuilt) │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_4 (Dropout)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_6 (Dropout)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼──────────────

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
early_stop=tensorflow.keras.callbacks.EarlyStopping(
     monitor='val_loss',  # Monitors validation loss
    patience=3,          # Stops training after 3 epochs with no improvement
    restore_best_weights=True
)

In [28]:
optimizer = Adam(learning_rate=learning_rate)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"])



In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,y_train,y_test=train_test_split(pad_sequenced,label,random_state=0,test_size=0.3)

In [31]:
from tensorflow.keras.utils import to_categorical

# Assuming y_train and y_test are integers representing class labels
y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)

In [32]:
y_train

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [33]:
X_train

array([[ 3, 90, 13, ...,  0,  0,  0],
       [26, 27,  8, ...,  0,  0,  0],
       [ 3, 90, 13, ...,  0,  0,  0],
       ...,
       [56, 55,  8, ...,  0,  0,  0],
       [26, 27,  8, ...,  0,  0,  0],
       [ 3, 41, 40, ...,  0,  0,  0]])

In [34]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=15,batch_size=32,callbacks=[early_stop])

Epoch 1/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 847s 4s/step - accuracy: 0.3323 - loss: nan - val_accuracy: 0.3313 - val_loss: nan
Epoch 2/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 827s 4s/step - accuracy: 0.3477 - loss: nan - val_accuracy: 0.3313 - val_loss: nan
Epoch 3/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 827s 4s/step - accuracy: 0.3469 - loss: nan - val_accuracy: 0.3313 - val_loss: nan


In [35]:

text="Climate change is one of the most pressing challenges of our time. Human activities such as deforestation and the burning of fossil fuels have resulted in increased greenhouse gas emissions. This has led t"

In [36]:
model.save("model2.keras")

In [37]:
from tensorflow.keras.models import load_model

In [38]:
model1 = load_model("model2.keras")


In [39]:
# tokenizer = Tokenizer(oov_token="<OOV>")  # Set a vocabulary size
# tokenizer.fit_on_texts([text])          # Fit tokenizer on text
sequence = token.texts_to_sequences([text]) 

In [40]:
text_sequences=pad_sequences(sequence,maxlen=sequence_length, padding='post')

In [41]:
ans=model.predict(text_sequences)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 822ms/step


In [42]:
ans

array([[0.3235347 , 0.3445329 , 0.33193237]], dtype=float32)

In [43]:
labels[ans.argmax()]

'Human-Written'

In [44]:
text_sequences

array([[ 56,  55,   8,  57,   5,   3,  58,  59,  60,   5,  61,  62,  63,
         64,  65,  66,  67,   2,   3,  16,   5,  17,  18,  25,  68,   7,
         69,  19,  70,  71,  20,  21,  11, 173,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0